### ISSUE TITLE
Achieve image classes reconstruction based on EEG signal

### ISSUE THREAD

**Issue by stefanches7** [stefanches7/DeepVisual#1]
Data from the study [by Rashkov G. et al. (2019)](https://doi.org/10.1101/787101) is accessible at https://data.mendeley.com/datasets/s2dxrv45fr/1. In it, EEG signals are annotated with information about the one of the classes of visual stimulus shown to the participant (animal movement, abstract figures etc. - refer to study for more details). 
The first and most simple goal is to predict seen image class based on EEG signal during the viewing.

**TODO**:
- [x] Extract sequences, assign session and seen image class
- [ ] Signal aggregation - e.g. Discrete Wavelet Transformation
- [x] Deep Learning model 
Currently MLP, but can try other e.g. Deep Belief Networks
- [x] Test/train split
- [ ] Prediction - does not finish on laptop, have to scale
- [ ] Evaluation of results
