### ISSUE TITLE
EEG signal transformation

### ISSUE THREAD

**Issue by stefanches7** [stefanches7/DeepVisual#2]
At the end, EEG signal can be represented as n*m matrix, where n is the number of channels in EEG helmet (64 or 128) and m is the number of taken discrete time points.
Usually, signals are being transformed to add information quotient/distropy to each feature (Physics specialists are welcome to tell more!). We might want to also pick one transformation method and see whether it helps our pipeline.
**TODO**
- [ ] (newcomer suggested) Read https://doi.org/10.1101/787101 on tranformation _before_ ICA
- [ ] (newcomer suggested) Read about Discrete wavelet transformation
- [ ] PIck transformation method
- [ ] Evaluate compared to baseline (no transformation)
